image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1206.9137 ,    0.     ,  959.15657,
            0.     , 1207.06304,  539.52982,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.000281, -0.000158, 0.000051, -0.000111, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1206.48865,    0.     ,  958.37544,    0.     ,
            0.     , 1206.30798,  539.10566,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
